version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.1
  aws-ecr: circleci/aws-ecr@9.0

jobs:
  build-and-push-image:
    machine:
      image: ubuntu-2204:current
    steps:
      - aws-ecr/build-and-push-image:
          account_id: ${AWS_ACCOUNT_ID}
          region: ${AWS_DEFAULT_REGION}
          create-repo: true
          dockerfile: Dockerfile
          path: .
          repo: boxie/planka
          tag: "$CIRCLE_SHA1"

workflows:
  deploy:
    jobs:
      - build-and-push-image:
          context: aws-prod
